name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: main
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            cd ~/procon33_RemoteTravelers_python/
            git pull origin main
            git add .
            git commit -m "ServerUpdate"
            git push origin main
